version: '3.8'
services:
  service:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
          - 8000:8000


  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - .env
    volumes:
      - service_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  service_pgdata: